"""HTML reporter using Jinja2 templates with Plotly charts."""
# ruff: noqa: E501

from __future__ import annotations

import json
from pathlib import Path

from jinja2 import Template

from agentbench.models import ScoreReport

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AgentBench Security Report - {{ report.agent_id }}</title>
    <script src="https://cdn.plot.ly/plotly-2.35.0.min.js"></script>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0f172a; color: #e2e8f0; padding: 2rem; }
        .container { max-width: 960px; margin: 0 auto; }
        h1 { font-size: 1.8rem; margin-bottom: 0.5rem; }
        h2 { font-size: 1.3rem; margin: 1.5rem 0 0.75rem; color: #94a3b8; }
        .meta { color: #64748b; margin-bottom: 1.5rem; }
        .score-card { background: #1e293b; border-radius: 12px; padding: 1.5rem; margin-bottom: 1rem; }
        .score-value { font-size: 3rem; font-weight: 700; }
        .score-bar { height: 12px; background: #334155; border-radius: 6px; margin-top: 0.75rem; overflow: hidden; }
        .score-fill { height: 100%; border-radius: 6px; transition: width 0.5s; }
        .categories { display: grid; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); gap: 1rem; }
        .cat-card { background: #1e293b; border-radius: 8px; padding: 1rem; }
        .cat-name { font-weight: 600; margin-bottom: 0.5rem; }
        .cat-score { font-size: 1.5rem; font-weight: 700; }
        .cat-stats { font-size: 0.85rem; color: #64748b; margin-top: 0.25rem; }
        table { width: 100%; border-collapse: collapse; margin-top: 1rem; }
        th { text-align: left; padding: 0.5rem; color: #94a3b8; font-size: 0.85rem; border-bottom: 1px solid #334155; }
        td { padding: 0.5rem; border-bottom: 1px solid #1e293b; }
        .passed { color: #22c55e; }
        .failed { color: #ef4444; }
        .skipped { color: #eab308; }
        .high { color: #22c55e; }
        .medium { color: #eab308; }
        .low { color: #ef4444; }
        .chart-container { background: #1e293b; border-radius: 12px; padding: 1rem; margin-bottom: 1rem; }
        .footer { text-align: center; color: #64748b; font-size: 0.85rem; margin-top: 2rem; }
    </style>
</head>
<body>
    <div class="container">
        <h1>AgentBench Security Report</h1>
        <p class="meta">Agent: {{ report.agent_id }} {{ report.agent_version }} | {{ report.timestamp }} | {{ report.duration_seconds }}s</p>

        <div class="score-card">
            <div class="score-value {% if report.overall_score >= 80 %}high{% elif report.overall_score >= 50 %}medium{% else %}low{% endif %}">{{ "%.1f"|format(report.overall_score) }}</div>
            <div>Overall Security Score (out of 100)</div>
            <div class="score-bar">
                <div class="score-fill {% if report.overall_score >= 80 %}high{% elif report.overall_score >= 50 %}medium{% else %}low{% endif %}" style="width: {{ report.overall_score }}%"></div>
            </div>
            <div class="cat-stats">Tests: {{ report.passed_tests }} passed / {{ report.failed_tests }} failed ({{ report.total_tests }} total)</div>
        </div>

        <div class="chart-container">
            <div id="categoryChart"></div>
        </div>

        <h2>Category Scores</h2>
        <div class="categories">
            {% for cat in report.categories %}
            <div class="cat-card">
                <div class="cat-name">{{ cat.name }}</div>
                <div class="cat-score {% if cat.score >= 80 %}high{% elif cat.score >= 50 %}medium{% else %}low{% endif %}">{{ "%.1f"|format(cat.score) }}</div>
                <div class="cat-stats">{{ cat.tests_passed }}/{{ cat.tests_total }} passed</div>
                <div class="score-bar"><div class="score-fill {% if cat.score >= 80 %}high{% elif cat.score >= 50 %}medium{% else %}low{% endif %}" style="width: {{ cat.score }}%"></div></div>
            </div>
            {% endfor %}
        </div>

        <h2>Test Results</h2>
        <table>
            <tr><th>ID</th><th>Name</th><th>Category</th><th>Status</th><th>Score</th></tr>
            {% for r in report.results %}
            <tr>
                <td>{{ r.test_case.id }}</td>
                <td>{{ r.test_case.name }}</td>
                <td>{{ r.test_case.category }}</td>
                <td class="{{ r.status.value }}">{{ r.status.value }}</td>
                <td>{{ "%.1f"|format(r.score) }}</td>
            </tr>
            {% endfor %}
        </table>

        <div class="footer">Generated by AgentBench v0.1.0</div>
    </div>

    <script>
        var categories = {{ chart_data.categories | safe }};
        var scores = {{ chart_data.scores | safe }};
        var colors = scores.map(function(s) {
            if (s >= 80) return '#22c55e';
            if (s >= 50) return '#eab308';
            return '#ef4444';
        });

        var data = [{
            type: 'bar',
            x: categories,
            y: scores,
            marker: { color: colors },
            text: scores.map(function(s) { return s.toFixed(1) + '/100'; }),
            textposition: 'outside',
            hovertemplate: '%{x}: %{y:.1f}/100<extra></extra>'
        }];

        var layout = {
            title: { text: 'Security Scores by Category', font: { color: '#e2e8f0' } },
            paper_bgcolor: '#1e293b',
            plot_bgcolor: '#1e293b',
            font: { color: '#94a3b8' },
            xaxis: { tickfont: { color: '#94a3b8' }, gridcolor: '#334155' },
            yaxis: { range: [0, 100], tickfont: { color: '#94a3b8' }, gridcolor: '#334155' },
            margin: { t: 40, r: 20, b: 60, l: 60 },
            bargap: 0.3
        };

        Plotly.newPlot('categoryChart', data, layout, { responsive: true, displayModeBar: false });
    </script>
</body>
</html>
"""


class HTMLReporter:
    """Generates HTML reports from benchmark results using Jinja2 templates with Plotly charts."""

    def __init__(self) -> None:
        self._template = Template(HTML_TEMPLATE)

    def generate(self, report: ScoreReport) -> str:
        """Generate an HTML string from a score report.

        Args:
            report: Score report to render.

        Returns:
            HTML string with embedded Plotly charts.
        """
        chart_data = {
            "categories": json.dumps([c.name for c in report.categories]),
            "scores": json.dumps([round(c.score, 1) for c in report.categories]),
        }
        return self._template.render(report=report, chart_data=chart_data)

    def save(self, report: ScoreReport, filepath: str | Path) -> str:
        """Save a score report as an HTML file.

        Args:
            report: Score report to save.
            filepath: Output file path.

        Returns:
            Path to the saved file.
        """
        from agentbench.utils.security import safe_resolve_path

        path = safe_resolve_path(filepath)
        path.parent.mkdir(parents=True, exist_ok=True)
        html = self.generate(report)
        path.write_text(html)
        return str(path)
