"""Markdown reporter for benchmark results."""

from __future__ import annotations

from pathlib import Path

from agentbench.models import ScoreReport


class MarkdownReporter:
    """Generates Markdown reports from benchmark results."""

    def generate(self, report: ScoreReport) -> str:
        """Generate a Markdown string from a score report.

        Args:
            report: Score report to render.

        Returns:
            Markdown string.
        """
        lines: list[str] = []
        lines.append(f"# AgentBench Security Report: {report.agent_id}\n")
        lines.append(f"- **Agent**: {report.agent_id} {report.agent_version}")
        lines.append(f"- **Timestamp**: {report.timestamp}")
        lines.append(f"- **Duration**: {report.duration_seconds}s")
        lines.append(f"- **Overall Score**: {report.overall_score:.1f}/100\n")

        lines.append("## Summary\n")
        lines.append("| Metric | Value |")
        lines.append("|--------|-------|")
        lines.append(f"| Total Tests | {report.total_tests} |")
        lines.append(f"| Passed | {report.passed_tests} |")
        lines.append(f"| Failed | {report.failed_tests} |")
        lines.append(f"| Pass Rate | {self._pass_rate(report):.1f}% |\n")

        lines.append("## Category Scores\n")
        lines.append("| Category | Score | Passed | Failed | Total |")
        lines.append("|----------|-------|--------|--------|-------|")
        for cat in report.categories:
            lines.append(f"| {cat.name} | {cat.score:.1f} | {cat.tests_passed} | {cat.tests_failed} | {cat.tests_total} |")

        lines.append("\n## Test Results\n")
        lines.append("| ID | Name | Status | Score |")
        lines.append("|----|------|--------|-------|")
        for r in report.results:
            lines.append(f"| {r.test_case.id} | {r.test_case.name} | {r.status.value} | {r.score:.1f} |")

        lines.append("\n---\n*Generated by AgentBench v0.1.0*")
        return "\n".join(lines)

    def save(self, report: ScoreReport, filepath: str | Path) -> str:
        """Save a score report as a Markdown file.

        Args:
            report: Score report to save.
            filepath: Output file path.

        Returns:
            Path to the saved file.
        """
        from agentbench.utils.security import safe_resolve_path

        path = safe_resolve_path(filepath)
        path.parent.mkdir(parents=True, exist_ok=True)
        md = self.generate(report)
        path.write_text(md)
        return str(path)

    @staticmethod
    def _pass_rate(report: ScoreReport) -> float:
        if report.total_tests == 0:
            return 0.0
        return (report.passed_tests / report.total_tests) * 100.0
